[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
flary_token_sale = "2EBs8GKZGfrnQSdhQfHmxa1Mik2UgGXRV6kRjS4h8G8T"

[programs.devnet]
flary_token_sale = "2EBs8GKZGfrnQSdhQfHmxa1Mik2UgGXRV6kRjS4h8G8T"

[programs.mainnet]
flary_token_sale = "2EBs8GKZGfrnQSdhQfHmxa1Mik2UgGXRV6kRjS4h8G8T"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "../node_modules/.bin/jest --preset ts-jest"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[test.validator]
bind_address = "127.0.0.1"
ledger = ".anchor/test-ledger"
rpc_port = 8899
